### ISSUE TITLE
resourceIdsByHrefMap sometimes undefined in RichContent.js

### ISSUE THREAD

**Issue by aaronshaf** [instructure/common-cartridge-viewer#28]
[Dev example](http://localhost:3000/?src=https://s3.amazonaws.com/public-imscc/faa3332ffd834070ad81d97bdb236649.imscc#/resources/ibd9e0f058ab0d9fc28101072f140fb33) (localhost link)

**Comment by aaronshaf** [comment]
Worth another look. Might not be an issue anymore.

**Comment by RobertDHanna** [comment]
I wasn't able to reproduce this in the given example, but I'll keep an eye out for it.
